## Generated by terraform apply — do not edit by hand (see terraform/outputs.tf).
## Ansible connects as the default Ubuntu cloud-init user; hardening.yml locks this down.
##
## 3-server RKE2 HA control plane: rke2_server_init bootstraps the etcd cluster,
## rke2_server_join joins the other two. Both are full (schedulable) RKE2 servers —
## see ansible/inventory/group_vars/all.yml.

[mgmt]
${mgmt_hostname} ansible_host=${mgmt_ip}

[rke2_server_init]
${bootstrap_hostname} ansible_host=${bootstrap_ip}

[rke2_server_join]
%{ for h in join_hosts ~}
${h.hostname} ansible_host=${h.ip}
%{ endfor ~}

[rke2_server:children]
rke2_server_init
rke2_server_join

[routa:children]
mgmt
rke2_server

[routa:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/routa_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
