## Generated by terraform apply — do not edit by hand (see terraform/outputs.tf).
##
## ansible_user is root because Verda's minimal ubuntu-24.04 image seeds the SSH key
## to root, NOT to an `ubuntu` user (verified 2026-08-17 — see docs/decisions.md
## Section 15). Root is the bootstrap identity only: the hardening play creates a
## non-root admin user, installs the same key for it, then disables root SSH login.
## Every play after hardening overrides ansible_user to that admin user via play vars.
##
## 3-server RKE2 HA control plane: rke2_server_init bootstraps the etcd cluster,
## rke2_server_join joins the other two. Both are full (schedulable) RKE2 servers —
## see ansible/inventory/group_vars/all.yml.

[mgmt]
${mgmt_hostname} ansible_host=${mgmt_ip}

[rke2_server_init]
${bootstrap_hostname} ansible_host=${bootstrap_ip}

[rke2_server_join]
%{ for h in join_hosts ~}
${h.hostname} ansible_host=${h.ip}
%{ endfor ~}

[rke2_server:children]
rke2_server_init
rke2_server_join

[routa:children]
mgmt
rke2_server

[routa:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/routa_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
